package ecrf

import (
	"fmt"

	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/service/ecr"
	"github.com/aws/aws-sdk-go/service/iam"
)

const (
	PullerPolicyName  = "ecr-pull-%s"
	PullerDescription = "Pull %s from repository policy. Generated by ecr-factory"
)

// CreatePolicy create policy
func CreatePolicy(i iam.IAM, repo *ecr.Repository) (*iam.Policy, error) {
	param, err := pulleerParam(repo)
	if err != nil {
		return nil, err
	}

	resp, err := i.CreatePolicy(param)
	if err != nil {
		return nil, err
	}

	return resp.Policy, nil
}

func pulleerParam(repo *ecr.Repository) (*iam.CreatePolicyInput, error) {
	param := &iam.CreatePolicyInput{
		PolicyName:  aws.String(fmt.Sprintf(PullerPolicyName, *(repo.RepositoryName))),
		Description: aws.String(fmt.Sprintf(PullerDescription, *(repo.RepositoryName))),
	}

	return param, nil
}
